version: '3.8'

networks:
  soil-net:
    external: true


services:
  frontend:
    build: docker/
    entrypoint: docker/entrypoint.sh
    container_name: soil-front
    networks:
      - soil-net  # Mantido conforme definido
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app